version: "3"
services:
    linebot:
        build:
            context: .
            dockerfile: dockerfile
        network_mode: host
        volumes:
            - $PWD/../:/linebot
        working_dir: /linebot
        