From ubuntu:16.04 as dev_env

RUN apt-get update && apt-get install -y software-properties-common \
          python3-pip
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update && apt-get install -y python3.6 
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
RUN update-alternatives --config python3
RUN pip3 install line-bot-sdk \
         flask
